### PR TITLE
Set default geometry to 2017 geometry

### PR DESCRIPTION
**Pull request by alja**
Please include this this change to 90X and future releases

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by mrodozov** [comment]
First i'm testing it with 9_2_X, and if it goes well (which is expected as those files are new ?) i'll backport it to 9_0_X and 9_1_X. You can follow the progress here https://github.com/cms-sw/cmsdist/pull/3034

**Comment by mrodozov** [comment]
The changes passed testing for 92X, you can follow their backporting to 91X and 90X from the links above. Cheers

**Comment by alja** [comment]
@mrodozov 
Thanks a lot for the fast response!

**Comment by alja** [comment]
@mrodozov 
These are geometry  files for Fireworks event display.

**Pull request merged**
