### PR TITLE
Update Reco Geometry Including new Hcal DetIds

### PR DESCRIPTION
**Pull request by ianna**
* New run 2 reco geometry
* Default is run 2 geometry

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by degano** [comment]
@ianna cmsbot doesn't know how to test this. Luckily I do! Which release are these files targeted to?

**Comment by ianna** [comment]
@degano - 81x for sure, most probably 80x as well. I'm testing how far behind we should go, will let you in a minute.

**Comment by ianna** [comment]
@degano - please, update it for both 80x and 81x

**Pull request merged**
